config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
  resources :topics
  resources :helplines
  resources :maintenance_receipts
  resources :comments

  get '/topic_comments/:id' => 'topics#comments', as: :topic_comments
  patch '/topic_status/:topic_id/:status' => 'topics#update_status', as: :topic_status

  get "members", to: "members#home", as: :home

  root to: 'members#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :society
  belongs_to :member
  has_many :comments, as: :commentable
  validates :member, :society, :title, :description, :status, presence: true
  enum status: { unresolved: 0, resolved: 1 }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = current_society.topics.paginate(page: params[:page], per_page: 10)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = current_member.topics.build(society: current_member.society)
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_member.topics.build(topic_params)
    @topic.society = current_member.society

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comments
    topic = Topic.find params[:id]
    @comments = topic.comments
    @new_comment = topic.comments.build(member: current_member)
  end

  def update_status
    topic = Topic.find(params[:topic_id])
    topic.send("#{params[:status]}!")
    @element_id = "#{params[:topic_id]}_#{params[:status]}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_comment_box.html.erb
<% comments.each do |comment| %>
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= comment.member.gravatar_url %>" alt="...">
      </a>
    </div>
    <div class="media-body">
      <p class="media-heading"><%= comment.member %></p>
      <h5> <%= comment.content %> </h5>
    </div>
  </div>
<% end  %>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter description" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>
</br>

app/views/topics/_topic.html.erb
<div class="list-group">
<%= link_to topic_comments_path(topic), remote: true, class: "list-group-item" do %>
  <span class="list-group-item-heading topic-title"><%= topic.title %></span> <span class="label label-default"><%= "#{time_ago_in_words(topic.created_at)} ago"%></span>
  <h5 class="list-group-item-text"><%= topic.description %> </h5>
<% end %>
</div>

app/views/topics/_topic_actions.html.erb
<% if current_member.is_secretary? %>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= topic.status.titleize %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% Topic.statuses.each do |key, val| %>
      <li class="<%= topic.status == key ? 'active' : '' %>">
        <%= link_to key.titleize, "topic_status/#{topic.id}/#{key}", method: :patch, id: "#{topic.id}_#{key}", remote: true %>
      </li>
  	<% end %>
    </ul>
  </div>
  <% else %>
   <button class="btn btn-disabled" type="button">
     <%= topic.status.titleize %>
   </button>
<% end %>

<% if topic.member == current_member %>
  <%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-link' %>
  <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link'%>
<%end%>

app/views/topics/comments.js.erb
$('#CommentModal').find('.modal-title').html("Comments <%= @comments.count %>")
$('#CommentModal').find('.modal-footer').html("<%= escape_javascript(render('comments/new', comment: @new_comment)) %>")
$('#CommentModal').find('.modal-body').html("<%= escape_javascript(render('shared/comment_box', comments: @comments.reload)) %>")
$('#CommentModal').modal()

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic, class: "btn btn-link" %> |
<%= link_to 'Back', topics_path, class: "btn btn-link" %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Topics</h1>

<% @topics.each do |topic| %>
  <div class="row">
    <div class="col-sm-10">
      <%= render 'topic', topic: topic %>
    </div>
    <div class="col-sm-2">
      <%= render 'topic_actions', topic: topic %>
    </div>
  </div>
<% end %>

<%= link_to 'New Topic', new_topic_path, class: "btn btn-link" %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<br>
<%= link_to 'Back', topics_path, class: "btn btn-link" %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @topic.title %></p>
<p><%= @topic.description %></p>

<% if(current_member.is_secretary? || ( topic.member == current_member)) %>
  <%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', topics_path, class: "btn btn-link" %>

app/views/topics/update_status.js.erb
window.location.reload();