config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
  resources :topics
  resources :helplines
  resources :maintenance_receipts
  resources :comments

  get '/topic_comments/:id' => 'topics#comments', as: :topic_comments
  patch '/topic_status/:topic_id/:status' => 'topics#update_status', as: :topic_status

  get "members", to: "members#home", as: :home

  root to: 'members#home'
end

app/models/maintenance_receipt.rb
class MaintenanceReceipt < ApplicationRecord
  belongs_to :society

  has_attached_file :receipt
  validates_attachment :receipt,
   content_type: { content_type: ['application/pdf'] }

   validates_uniqueness_of :month, scope: :year
end

app/controllers/maintenance_receipts_controller.rb
class MaintenanceReceiptsController < ApplicationController
  before_action :set_maintenance_receipt, only: [:show, :edit, :update, :destroy]

  # GET /maintenance_receipts
  # GET /maintenance_receipts.json
  def index
    @maintenance_receipts = current_society.maintenance_receipts.paginate(page: params[:page], per_page: 10)
  end

  # GET /maintenance_receipts/1
  # GET /maintenance_receipts/1.json
  def show
  end

  # GET /maintenance_receipts/new
  def new
    @maintenance_receipt = current_society.maintenance_receipts.new
  end

  # GET /maintenance_receipts/1/edit
  def edit
  end

  # POST /maintenance_receipts
  # POST /maintenance_receipts.json
  def create
    @maintenance_receipt = current_society.maintenance_receipts.new(maintenance_receipt_params)

    respond_to do |format|
      if @maintenance_receipt.save
        format.html { redirect_to @maintenance_receipt, notice: 'Maintenance receipt was successfully created.' }
        format.json { render :show, status: :created, location: @maintenance_receipt }
      else
        format.html { render :new }
        format.json { render json: @maintenance_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_receipts/1
  # PATCH/PUT /maintenance_receipts/1.json
  def update
    respond_to do |format|
      if @maintenance_receipt.update(maintenance_receipt_params)
        format.html { redirect_to @maintenance_receipt, notice: 'Maintenance receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @maintenance_receipt }
      else
        format.html { render :edit }
        format.json { render json: @maintenance_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_receipts/1
  # DELETE /maintenance_receipts/1.json
  def destroy
    @maintenance_receipt.destroy
    respond_to do |format|
      format.html { redirect_to maintenance_receipts_url, notice: 'Maintenance receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_receipt
      @maintenance_receipt = MaintenanceReceipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maintenance_receipt_params
      params.require(:maintenance_receipt).permit(:receipt, :society_id, :month, :year)
    end
end

app/helpers/maintenance_receipts_helper.rb
module MaintenanceReceiptsHelper
end

app/views/maintenance_receipts/_form.html.erb
<%= form_for(maintenance_receipt) do |f| %>
  <% if maintenance_receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maintenance_receipt.errors.count, "error") %> prohibited this maintenance_receipt from being saved:</h2>

      <ul>
      <% maintenance_receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :receipt %>
    <%= f.file_field :receipt, class: 'form-control', accept: 'application/pdf'%>
  </div>

  <div class="form-group">
    <%= f.label :month %>
    <%= f.select :month, (1)..(12), selected: Time.zone.now.month %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.select :year, (Time.zone.now.year - 5)..(Time.zone.now.year), selected: Time.zone.now.year %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>
</br>

app/views/maintenance_receipts/edit.html.erb
<h1>Editing Maintenance Receipt</h1>

<%= render 'form', maintenance_receipt: @maintenance_receipt %>

<%= link_to 'Show', @maintenance_receipt, class: "btn btn-link" %> |
<%= link_to 'Back', maintenance_receipts_path, class: "btn btn-link" %>

app/views/maintenance_receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maintenance Receipts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> Month </th>
      <th> Year </th>
      <th> Receipt </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_receipts.each do |maintenance_receipt| %>
      <tr>
        <td><%= maintenance_receipt.month %></td>
        <td><%= maintenance_receipt.year %></td>
        <td><%= link_to maintenance_receipt.receipt.original_filename, maintenance_receipt.receipt.url, target: '_blank' %></td>
        <td><%= link_to 'Show', maintenance_receipt %></td>
        <% if(current_member.is_secretary?) %>
          <td><%= link_to 'Edit', edit_maintenance_receipt_path(maintenance_receipt) %></td>
          <td><%= link_to 'Destroy', maintenance_receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if(current_member.is_secretary?) %>
  <%= link_to 'New Maintenance Receipt', new_maintenance_receipt_path, class: "btn btn-link" %>
<% end %>

app/views/maintenance_receipts/new.html.erb
<h1>New Maintenance Receipt</h1>

<%= render 'form', maintenance_receipt: @maintenance_receipt %>

<%= link_to 'Back', maintenance_receipts_path, class: "btn btn-link" %>

app/views/maintenance_receipts/show.html.erb
<p id="notice"><%= notice %></p>
<p> Month :<%= @maintenance_receipt.month %></p>
<p> Year : <%= @maintenance_receipt.year %></p>
<p> Receipt : <%= link_to @maintenance_receipt.receipt.original_filename, @maintenance_receipt.receipt.url, target: '_blank' %></p>
<% if(current_member.is_secretary?) %>
  <%= link_to 'Edit', edit_maintenance_receipt_path(@maintenance_receipt), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', maintenance_receipts_path, class: "btn btn-link" %>