config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
  resources :topics
  resources :helplines
  resources :maintenance_receipts
  resources :comments

  get '/topic_comments/:id' => 'topics#comments', as: :topic_comments
  patch '/topic_status/:topic_id/:status' => 'topics#update_status', as: :topic_status

  get "members", to: "members#home", as: :home

  root to: 'members#home'
end

app/models/helpline.rb
class Helpline < ApplicationRecord
  belongs_to :region
  belongs_to :helpline_category
  validates :address, :name, :helpline_category, :region, :email_address, presence: true
end

app/controllers/helplines_controller.rb
class HelplinesController < ApplicationController
  before_action :set_helpline, only: [:show, :edit, :update, :destroy]

  # GET /helplines
  # GET /helplines.json
  def index
    @helplines = current_region.helplines.paginate(page: params[:page], per_page: 10)
  end

  # GET /helplines/1
  # GET /helplines/1.json
  def show
  end

  # GET /helplines/new
  def new
    @helpline = current_region.helplines.new
  end

  # GET /helplines/1/edit
  def edit
  end

  # POST /helplines
  # POST /helplines.json
  def create
    @helpline = current_region.helplines.build(helpline_params)

    respond_to do |format|
      if @helpline.save
        format.html { redirect_to @helpline, notice: 'Helpline was successfully created.' }
        format.json { render :show, status: :created, location: @helpline }
      else
        format.html { render :new }
        format.json { render json: @helpline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helplines/1
  # PATCH/PUT /helplines/1.json
  def update
    respond_to do |format|
      if @helpline.update(helpline_params)
        format.html { redirect_to @helpline, notice: 'Helpline was successfully updated.' }
        format.json { render :show, status: :ok, location: @helpline }
      else
        format.html { render :edit }
        format.json { render json: @helpline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helplines/1
  # DELETE /helplines/1.json
  def destroy
    @helpline.destroy
    respond_to do |format|
      format.html { redirect_to helplines_url, notice: 'Helpline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helpline
      @helpline = Helpline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helpline_params
      params.require(:helpline).permit(:name, :address, :phone_number, :mobile_number, :helpline_category_id)
    end
end

app/helpers/helplines_helper.rb
module HelplinesHelper
end

app/views/helplines/_form.html.erb
<%= form_for(helpline) do |f| %>
  <% if helpline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(helpline.errors.count, "error") %> prohibited this helpline from being saved:</h2>

      <ul>
      <% helpline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :helpline_category %>
    <%= f.select :helpline_category_id, options_from_collection_for_select(HelplineCategory.all, :id, :name, helpline.helpline_category_id.to_i), class: "form-control", placeholder: "Select your helpline category" %>
  </div>

  <div class="form-group">
    <%= f.label :region %>
    <%= f.select :region_id, options_from_collection_for_select(Region.all, :id, :name, helpline.region_id.to_i), class: "form-control", placeholder: "Select your region" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Name" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", placeholder: "Enter Address" %>
  </div>

    <div class="form-group">
      <%= f.label :email_address %>
      <%= f.email_field :email_address, class: "form-control", placeholder: "Valid email under 255 characters" %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", placeholder: "not more than 10 digits" %>
    </div>

    <div class="form-group">
      <%= f.label :mobile_number %>
      <%= f.text_field :mobile_number, class: "form-control", placeholder: "not more than 10 digits" %>
    </div>

  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>
</br>

app/views/helplines/edit.html.erb
<h1>Editing Helpline</h1>

<%= render 'form', helpline: @helpline %>

<%= link_to 'Show', @helpline, class: "btn btn-default" %> |
<%= link_to 'Back', helplines_path, class: "btn btn-default" %>

app/views/helplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Helplines</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> Name </th>
      <th> Address </th>
      <th> Phone Number </th>
      <th> Mobile Number </th>
      <th> Email Address </th>
      <th> Region </th>
      <th> Category </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helplines.each do |helpline| %>
      <tr>
        <td><%= helpline.name %></td>
        <td><%= helpline.address %></td>
        <td><%= helpline.phone_number %></td>
        <td><%= helpline.mobile_number %></td>
        <td><%= helpline.email_address %></td>
        <td><%= helpline.region.to_s %></td>
        <td><%= helpline.helpline_category.to_s %></td>
        <td><%= link_to 'Show', helpline %></td>
        <% if(current_member.is_secretary?) %>
          <td><%= link_to 'Edit', edit_helpline_path(helpline) %></td>
          <td><%= link_to 'Destroy', helpline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
  <%= will_paginate @helplines, renderer: BootstrapPagination::Rails %>
</table>

<br>

<% if(current_member.is_secretary?) %>
  <%= link_to 'New Helpline', new_helpline_path, class: "btn btn-link" %>
<%end%>

app/views/helplines/new.html.erb
<h1>New Helpline</h1>

<%= render 'form', helpline: @helpline %>

<%= link_to 'Back', helplines_path, class: "btn btn-link" %>

app/views/helplines/show.html.erb
<p id="notice"><%= notice %></p>
<p> Name :<%= @helpline.name %></p>
<p> Address : <%= @helpline.address %></p>
<p> Phone Number : <%= @helpline.phone_number %></p>
<p> Mobile Number : <%= @helpline.mobile_number %></p>
<p> Email Address : <%= @helpline.email_address %></p>
<p> Region : <%= @helpline.region %></p>
<p> Category : <%= @helpline.helpline_category %></p>
<% if(current_member.is_secretary?) %>
  <%= link_to 'Edit', edit_helpline_path(@helpline), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', helplines_path, class: "btn btn-link" %>