config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
  resources :topics
  resources :helplines
  resources :maintenance_receipts
  resources :comments

  get '/topic_comments/:id' => 'topics#comments', as: :topic_comments
  patch '/topic_status/:topic_id/:status' => 'topics#update_status', as: :topic_status

  get "members", to: "members#home", as: :home

  root to: 'members#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :commentable, polymorphic: true
  validates :member, :content, presence: true
end

app/models/helpline.rb
class Helpline < ApplicationRecord
  belongs_to :region
  belongs_to :helpline_category
  validates :address, :name, :helpline_category, :region, :email_address, presence: true
end

app/models/helpline_category.rb
class HelplineCategory < ApplicationRecord
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/maintenance_receipt.rb
class MaintenanceReceipt < ApplicationRecord
  belongs_to :society

  has_attached_file :receipt
  validates_attachment :receipt,
   content_type: { content_type: ['application/pdf'] }

   validates_uniqueness_of :month, scope: :year
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, authentication_keys: [:email]
  belongs_to :society
  has_many :topics
  has_many :comments
  validates :email, :first_name, :last_name, :phone_number, :society, presence: true
  delegate :region_id, to: :society, allow_nil: true

  has_gravatar

  def to_s
    "#{first_name} #{last_name}".to_s.capitalize
  end
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :societies
  has_many :helplines, dependent: :destroy
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/society.rb
class Society < ApplicationRecord
  belongs_to :region
  has_many :members
  has_many :topics
  has_many :maintenance_receipts
  validates :registration_number, :region, :name, :address, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :society
  belongs_to :member
  has_many :comments, as: :commentable
  validates :member, :society, :title, :description, :status, presence: true
  enum status: { unresolved: 0, resolved: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_member!

  helper_method :current_region, :current_society

  def current_region
    current_society.region
  end

  def current_society
    current_member.society
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@new_comment = Comment.create(params.require(:comment).permit(
  		:commentable_id, :commentable_type, :content, :member_id))
  end
end

app/controllers/helplines_controller.rb
class HelplinesController < ApplicationController
  before_action :set_helpline, only: [:show, :edit, :update, :destroy]

  # GET /helplines
  # GET /helplines.json
  def index
    @helplines = current_region.helplines.paginate(page: params[:page], per_page: 10)
  end

  # GET /helplines/1
  # GET /helplines/1.json
  def show
  end

  # GET /helplines/new
  def new
    @helpline = current_region.helplines.new
  end

  # GET /helplines/1/edit
  def edit
  end

  # POST /helplines
  # POST /helplines.json
  def create
    @helpline = current_region.helplines.build(helpline_params)

    respond_to do |format|
      if @helpline.save
        format.html { redirect_to @helpline, notice: 'Helpline was successfully created.' }
        format.json { render :show, status: :created, location: @helpline }
      else
        format.html { render :new }
        format.json { render json: @helpline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helplines/1
  # PATCH/PUT /helplines/1.json
  def update
    respond_to do |format|
      if @helpline.update(helpline_params)
        format.html { redirect_to @helpline, notice: 'Helpline was successfully updated.' }
        format.json { render :show, status: :ok, location: @helpline }
      else
        format.html { render :edit }
        format.json { render json: @helpline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helplines/1
  # DELETE /helplines/1.json
  def destroy
    @helpline.destroy
    respond_to do |format|
      format.html { redirect_to helplines_url, notice: 'Helpline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helpline
      @helpline = Helpline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helpline_params
      params.require(:helpline).permit(:name, :address, :phone_number, :mobile_number, :helpline_category_id)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def home
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = current_society.topics.paginate(page: params[:page], per_page: 10)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = current_member.topics.build(society: current_member.society)
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_member.topics.build(topic_params)
    @topic.society = current_member.society

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comments
    topic = Topic.find params[:id]
    @comments = topic.comments
    @new_comment = topic.comments.build(member: current_member)
  end

  def update_status
    topic = Topic.find(params[:topic_id])
    topic.send("#{params[:status]}!")
    @element_id = "#{params[:topic_id]}_#{params[:status]}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helplines_helper.rb
module HelplinesHelper
end

app/helpers/maintenance_receipts_helper.rb
module MaintenanceReceiptsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
      <button class="nav" id="sidebarButton">
      <span id="bar1" class="icon-bar toggle"></span>
      <span id="bar2" class="icon-bar toggle"></span>
      <span id="bar3" class="icon-bar toggle"></span>
      </button>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <a>Menu
          <span class="caret"></span>
        </a>
      </button>
      <a class="navbar-brand" href="/">SDK</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to current_member ? "Hello #{current_member.first_name}!" : "Hello, Guest!", nil %></li>
        <% if current_member  %>
          <li>
            <a href="#">
              <img class="user-profile-image" src="<%= current_member.gravatar_url %>" alt="#{current_member.first_name}">
            </a>
          </li>
          <li> <%= link_to "Logout", destroy_session_path(current_member), method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Log in", new_member_session_path %> </li>
          <li><a>|</a></li>
          <li> <%= link_to "Sign up", new_member_registration_path %> </li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_modal.html.erb
<div id='CommentModal' class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel"></h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sdk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>
  <%= render 'layouts/modal' %>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="\members">Home</a></li>
            <%if current_member %>
              <li><a href="\topics">Topics</a></li>
              <li><a href="\helplines">Helplines</a></li>
              <li><a href="\maintenance_receipts">Maintenance Receipts</a></li>
            <%end%>
          </ul>
          <ul class="nav nav-sidebar" id="fileItems"></ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main toggle">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_comment_box.html.erb
<% comments.each do |comment| %>
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= comment.member.gravatar_url %>" alt="...">
      </a>
    </div>
    <div class="media-body">
      <p class="media-heading"><%= comment.member %> - 
        <small><%= "#{time_ago_in_words(comment.created_at)} ago"%></small>
        </p>
      <h5> <%= comment.content %> </h5>
    </div>
  </div>
<% end  %>